name: Awesome Fellowship
highlighter: pygments
gems:
 - jekyll-sitemap
collections: 
  profiles: 
    permalink: /profiles/:path/
    output: true
exclude: [Gemfile, Gemfile.lock, github.php, README.md]
include: [.htaccess]